### ISSUE TITLE
Portfolio module doesn't respect links

### ISSUE THREAD

**Issue by qumuq-til** [devlom/grav-theme-hola#1]
In Portfolio module the links you specify in the "Link" field don't appear to be working. Clicking on portfolio images or the chain icon on top left only opens a preview of the image itself with the ability to navigate between images.

There should be an option for Portfolio items to either be direct links to other pages or just act as a gallery.

That way we can repurpose the module to be a simple showcase of work/images within a blog post, or a collection of images on the front page that act as direct links to blog posts talking about different projects.

**Comment by Dzi0nek** [comment]
Link is working now. Fix uploaded

**Comment by qumuq-til** [comment]
I've reuploaded the theme folder without changing anything else and apparently while the link circle now works properly (i.e. linking to some website) just clicking on the image simply opens that jpeg in the browser - no gallery mode.

I think the best way to handle that would be to have two mutually exclusive options for Portfolio modules: whether the images behave like links or whether they behave like a simple gallery without links.

The reason for that is that users may (and will!) find it hard and unintuitive to have to click on the "link" circle on the top left rather than the image itself, most will definitely miss that icon, and will be baffled by just the image loading.

It should either be a js gallery so a user can click away and see other images in that Portfolio or a set of links for which the images don't even open instead taking the visitor directly to another page.

**Comment by qumuq-til** [comment]
The issue is closed, but I don't think it should be, in its current condition.

For the moment the Portfolio is definitely half-baked. Not least because clicking on an image should really lead to a gallery, just like it was in your original iteration and like it is at Styleshout. The only thing needed fixing was the circular link at the top left.

**Comment by hexplor** [comment]
Mate.. This is really obvious for us and it's staying as is :) Styleshout has a bug in their html template. When you hover, it clearly shows external link in the code

https://monosnap.com/direct/t1LWomyQIoRQOVHrLGQCYqZpjqamMd

It's just not properly implemented and we fixed that in grav theme. I think it's logical explanation. You click on link -> points to external project page. You click on photo, it shows larger one.

**Comment by qumuq-til** [comment]
Actually when you click on an image in Styleshout's demo it doesn't take you directly to a bare image, it takes you to a gallery.
