### ISSUE TITLE
Howto disable the Titel display at/in modular Page?

### ISSUE THREAD

**Issue by ohobby** [devlom/grav-theme-hola#30]
Hi,

how can i disable the Titel display at/in modular Page?

Thanks,
Oliver

**Comment by Dzi0nek** [comment]
Hi,

Grav requires for the title to be there on the admin side but you can delete/comment the line with title from html.twig of the section.

enjoy,
Matt

**Comment by ohobby** [comment]
Many thank, i take a look and think this is ok.
