### ISSUE TITLE
Ability to re-shuffle modules on modular pages

### ISSUE THREAD

**Issue by qumuq-til** [devlom/grav-theme-hola#7]
As someone new to Grav I'm again not sure if it's something intrinsic to the CMS or something missing in the theme, but I couldn't find a way to re-arrange the order of modules for any modular page (for example, Home). There's a way to manually edit that order in "Expert" mode by correcting the YAML file but no GUI.

New modules added to a modular page via GUI don't get added to that YAML file automatically, either.

**Comment by Dzi0nek** [comment]
Thank you for the feedback, we'll be going through every issue that we got to find the best solution. Thanks again!

**Comment by Dzi0nek** [comment]
You can always change the order of modular sections in modular page in expert mode. The GUI option may be added in the future.

**Comment by hexplor** [comment]
Fixed. You're now able to reorder stuff. It was a matter of adding number prefix for modular pages. Closing.
